spring:
  application:
    name: keystead-server
  datasource:
    url: jdbc:h2:file:./data/keystead-server;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: keystead
    password:
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: health,info

keystead:
  security:
    basic-auth-enabled: false
  automation:
    token-max-ttl: P90D
    rate-limit-requests-per-minute: 120
