spring:
  application:
    name: keystead-server
  datasource:
    url: jdbc:h2:file:./data/keystead-server;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: keystead
    password:
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
