create table personal_vaults (
    owner_id varchar(255) not null,
    fingerprint varchar(255) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (owner_id)
);

create table vault_record_events (
    server_sequence bigint generated by default as identity,
    owner_id varchar(255) not null,
    event_id varchar(128) not null,
    fingerprint varchar(255) not null,
    secret_id varchar(255) not null,
    local_revision bigint not null,
    secret_type varchar(64) not null,
    encrypted_profile text not null,
    envelope text not null,
    deleted boolean not null,
    created_at timestamp not null,
    primary key (server_sequence),
    constraint uq_vault_record_events_owner_event unique (owner_id, event_id),
    constraint ck_vault_record_events_revision check (local_revision > 0)
);

create index idx_vault_record_events_owner_sequence
    on vault_record_events (owner_id, server_sequence);
