package top.focess.keystead.server.audit;

public enum AuditEventType {
    RECORD_STORED,
    RECORD_DELETED,
    RECORD_REVISION_CONFLICT,
    KEY_PACKAGE_STORED,
    AUTOMATION_PRINCIPAL_STORED,
    AUTOMATION_PRINCIPAL_REVOKED,
    AUTOMATION_TOKEN_ISSUED,
    AUTOMATION_TOKEN_REVOKED,
    AUTOMATION_KEY_PACKAGE_STORED,
    RECOVERY_ENROLLMENT_CREATED,
    RECOVERY_ENROLLMENT_COMMITTED,
    RECOVERY_KEY_PACKAGE_STORED,
    RECOVERY_COMPLETED,
    DEVICE_REVOKED,
    VAULT_ROTATION_REQUIRED,
    VAULT_ROTATION_COMMITTED,
    VAULT_MEMBER_INVITED,
    VAULT_MEMBER_ACCEPTED,
    VAULT_MEMBER_DECLINED,
    VAULT_MEMBER_ROLE_CHANGED,
    VAULT_MEMBER_REMOVED,
    LOGIN_FAILED
}
