package top.focess.keystead.server.audit;

public enum AuditEventType {
    RECORD_STORED,
    RECORD_DELETED,
    RECORD_REVISION_CONFLICT,
    KEY_PACKAGE_STORED,
    AUTOMATION_PRINCIPAL_STORED,
    AUTOMATION_PRINCIPAL_REVOKED,
    AUTOMATION_TOKEN_ISSUED,
    AUTOMATION_TOKEN_REVOKED,
    AUTOMATION_KEY_PACKAGE_STORED,
    RECOVERY_ENROLLMENT_CREATED,
    RECOVERY_ENROLLMENT_COMMITTED,
    RECOVERY_KEY_PACKAGE_STORED,
    DEVICE_REVOKED,
    LOGIN_FAILED
}
